### ISSUE TITLE
trailing stop not working correctly 

### ISSUE THREAD

**Issue by in-elite** [cloggy45/Gekko-Bot-Resources#10]
this part not working correctly. 
`const currentPrice = candle.close;
	if(this.stopLoss.isTriggered(currentPrice)) {
		this.advice('short');
	    this.stopLoss.destroy();
	} else {
          // this part not working :-( 
	    this.stopLoss.update(currentPrice);
	}`

now i made some decision and start working, if price going up stop lost destroy preview stop lost and create new stop lost i don`t known why it's not updating preview stop lost but decision was so

    `if(currentPrice > this.stopLoss.isTriggered(currentPrice)){
			this.stopLoss.destroy();
			this.stopLoss.create(this.stopLoss.percentage, currentPrice);
		}
    if(this.stopLoss.isTriggered(currentPrice)) {
...........
`

**Comment by cloggy45** [comment]
Can you paste your client code?

**Comment by in-elite** [comment]
you mean strategy which I'm using?

**Comment by in-elite** [comment]
can you give to me your e-mail i send this strategy to you, it's not a public because it's combined from different strategies and code was taken from the authors on git hub 
my statege based on BBANDS+RSI+ADX_BULL_BEAR + your Trailing Stop Lost

**Comment by in-elite** [comment]
Backtest result of this strategy pair BTC/LTC 3 month from 01.01.2018 to 2018-02-27, time frame 45 minutes give profit 196.22102%

**Comment by John1231983** [comment]
Could you send it to my email too? john1231983@gmail.com   thanks

**Comment by cloggy45** [comment]
@in-elite My email is cloggy45@googlemail.com

**Comment by in-elite** [comment]
ok check your E-mail
