### ISSUE TITLE
mounirs-ga-version-1 stops at certain interval

### ISSUE THREAD

**Issue by shnmhrjn** [cloggy45/Gekko-Bot-Resources#15]
I was trying to run backtest but it stops in the middle.

![capture1](https://user-images.githubusercontent.com/7370408/45071927-5b017400-b0f8-11e8-853a-215a4862ac52.PNG)

I ran the backtest for a month but I stopped at 5 days,

What might be the issue?

Thanks and Regards,

**Comment by cloggy45** [comment]
@mounirlabaied
